# Generated by precisionFDA exporter (v1.0.3) on 2018-06-14 01:16:49 +0000
# The asset download links in this file are valid only for 24h.

# Exported app: rtg-core-variant-caller, revision: 8, authored by: isaac.liao
# https://precision.fda.gov/apps/app-Bz3fz1805v4p35FqBvb6z9P7

# For more information please consult the app export section in the precisionFDA docs

# Start with Ubuntu 14.04 base image
FROM ubuntu:14.04

# Install default precisionFDA Ubuntu packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \
	aria2 \
	byobu \
	cmake \
	cpanminus \
	curl \
	dstat \
	g++ \
	git \
	htop \
	libboost-all-dev \
	libcurl4-openssl-dev \
	libncurses5-dev \
	make \
	perl \
	pypy \
	python-dev \
	python-pip \
	r-base \
	ruby1.9.3 \
	wget \
	xz-utils

# Install default precisionFDA python packages
RUN pip install \
	requests==2.5.0 \
	futures==2.2.0 \
	setuptools==10.2

# Add DNAnexus repo to apt-get
RUN /bin/bash -c "echo 'deb http://dnanexus-apt-prod.s3.amazonaws.com/ubuntu trusty/amd64/' > /etc/apt/sources.list.d/dnanexus.list"
RUN /bin/bash -c "echo 'deb http://dnanexus-apt-prod.s3.amazonaws.com/ubuntu trusty/all/' >> /etc/apt/sources.list.d/dnanexus.list"
RUN curl https://wiki.dnanexus.com/images/files/ubuntu-signing-key.gpg | apt-key add -

# Install app-specific Ubuntu packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \
	openjdk-7-jre-headless

# Download app assets
RUN curl https://dl.dnanex.us/F/D/pVgvzZb36ggfF4V2FPpg5XgBYbYY8J65GXPjB8PQ/rtg-core-non-commercial-3.7-linux-x64.tar.gz | tar xzf - -C / --no-same-owner --no-same-permissions
RUN curl https://dl.dnanex.us/F/D/FbgGYP373XZYkk8v2VkV2YjbYqbYJG3y2yBQ82Qf/rtg-hs37d5.tar | tar xf - -C / --no-same-owner --no-same-permissions

# Download helper executables
RUN curl https://dl.dnanex.us/F/D/0K8P4zZvjq9vQ6qV0b6QqY1z2zvfZ0QKQP4gjBXp/emit-1.0.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions
RUN curl https://dl.dnanex.us/F/D/bByKQvv1F7BFP3xXPgYXZPZjkXj9V684VPz8gb7p/run-1.2.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions

# Write app spec and code to root folder
RUN ["/bin/bash","-c","echo -E \\{\\\"spec\\\":\\{\\\"input_spec\\\":\\[\\{\\\"name\\\":\\\"input\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"Input\\ BAM\\ file\\\",\\\"help\\\":\\\"Input\\ BAM\\ file\\ to\\ call\\ variants\\ on\\\"\\}\\],\\\"output_spec\\\":\\[\\{\\\"name\\\":\\\"output\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"Output\\ VCF\\ file\\\",\\\"help\\\":\\\"Output\\ VCF\\ file\\ containing\\ variants\\\"\\}\\],\\\"internet_access\\\":false,\\\"instance_type\\\":\\\"baseline-8\\\"\\},\\\"assets\\\":\\[\\\"file-Bz3f9P00qVbG4Xfqzxy8QYV2\\\",\\\"file-BqB6zV80qVb8Xb31P0B97jPg\\\"\\],\\\"packages\\\":\\[\\\"openjdk-7-jre-headless\\\"\\]\\} \u003e /spec.json"]
RUN ["/bin/bash","-c","echo -E \\{\\\"code\\\":\\\"\\\\n\\#if\\ \\[\\ -s\\ \\$bedfile_path\\ \\]\\\\n\\#\\ \\ then\\\\n\\#\\ \\ \\ \\ ../rtg-core-non-commercial-3.7/rtg\\ snp\\ -I\\ \\$input_path\\ -O\\ .\\ --region\\ \\$bedfile_path\\ --template\\ hs37d5.sdf\\\\n\\#\\ \\ else\\\\n../rtg-core-non-commercial-3.7/rtg\\ snp\\ -I\\ \\$input_path\\ -O\\ .\\ \\ --template\\ hs37d5.sdf\\\\n\\#fi\\\\n\\\\nemit\\ output\\ snps.vcf\\ \\\"\\} | python -c 'import sys,json; print json.load(sys.stdin)[\"code\"]' \u003e /script.sh"]

# Create directory /work and set it to $HOME and CWD
RUN mkdir -p /work
ENV HOME="/work"
WORKDIR /work

# Set entry point to container
ENTRYPOINT ["/usr/bin/run"]

VOLUME /data
VOLUME /work